image: gradle:latest

stages:
  - build
  - test
  - build-image
  - deploy

build-project:
  stage: build
  script:
    - ./gradlew --build-cache assemble

test-project:
  stage: test
  dependencies:
    - build-project
  script:
    - ./gradlew check

build-docker:
  image: docker:stable
  stage: build-image
  dependencies:
    - test-project
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t gasmartins/smartpayment-accounts .
    - docker push gasmartins/smartpayment-accounts:latest