image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
  stage: build
  script:
    - docker build -t gasmartins/smartpayment-accounts .
    - docker push gasmartins/smartpayment-accounts:latest