image: docker:stable

stages:
  - pre-build
  - build
  - test
  - deploy

build-docker:
  stage: pre-build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t gasmartins/smartpayment-accounts .
    - docker push gasmartins/smartpayment-accounts:latest

build-project:
  stage: build
  tags:
    - executor-task
  dependencies:
    - build-docker
  script:
    - echo "Runner"